name: AQUADYLIFE
description: "Aplicación Flutter para la gestión de productos, empleados y proveedores."

publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.4
  firebase_database: ^11.3.7
  firebase_storage: ^12.4.6
  google_sign_in: ^6.1.5
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  sensors_plus: ^4.0.0
  flutter_admin_scaffold: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png