name: AQUADYLIFE
description: "Aplicación Flutter para la gestión de productos, empleados y proveedores."

publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+4
  firebase_core: ^2.27.0
  cloud_firestore: ^4.17.5
  firebase_database: ^10.4.9
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

