// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9WMgL247ji_tJPfsMbaevhXz_fQWWrdQ',
    appId: '1:743170610984:web:37340dba98289407f7621d',
    messagingSenderId: '743170610984',
    projectId: 'aquadylife-2c254',
    authDomain: 'aquadylife-2c254.firebaseapp.com',
    storageBucket: 'aquadylife-2c254.firebasestorage.app',
    measurementId: 'G-83XHND2LBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuRrDCZJyMz5_k1Dyrwpp4Mgv1p60PNDU',
    appId: '1:743170610984:android:8c04833297438fd3f7621d',
    messagingSenderId: '743170610984',
    projectId: 'aquadylife-2c254',
    storageBucket: 'aquadylife-2c254.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwnWiCxZ4rhIaGncTrxd95lw5vMDRm-f4',
    appId: '1:743170610984:ios:7d735825dcc1659bf7621d',
    messagingSenderId: '743170610984',
    projectId: 'aquadylife-2c254',
    storageBucket: 'aquadylife-2c254.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwnWiCxZ4rhIaGncTrxd95lw5vMDRm-f4',
    appId: '1:743170610984:ios:7d735825dcc1659bf7621d',
    messagingSenderId: '743170610984',
    projectId: 'aquadylife-2c254',
    storageBucket: 'aquadylife-2c254.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9WMgL247ji_tJPfsMbaevhXz_fQWWrdQ',
    appId: '1:743170610984:web:a53c161c1bdb5d5ef7621d',
    messagingSenderId: '743170610984',
    projectId: 'aquadylife-2c254',
    authDomain: 'aquadylife-2c254.firebaseapp.com',
    storageBucket: 'aquadylife-2c254.firebasestorage.app',
    measurementId: 'G-TWY1KH0HNZ',
  );
}
